/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2026;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class ConsultaConsultorios extends javax.swing.JFrame {

    public Consultorio modificarConsultorio;
    private ArrayList<Usuario> doctoresDisponibles;
    private ArrayList<Usuario> secretariasDisponibles;
    private javax.swing.JPanel panelDoctores;
    private javax.swing.JPanel panelSecretarias;
    private ArrayList<JCheckBox> checksDoctores;
    private ArrayList<JCheckBox> checksSecretarias;

    /**
     * Creates new form ConsultaConsultorios
     */
    public ConsultaConsultorios() {
        initComponents();

        panelDoctores = new javax.swing.JPanel();
        panelDoctores.setLayout(new javax.swing.BoxLayout(panelDoctores, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(panelDoctores);

        panelSecretarias = new javax.swing.JPanel();
        panelSecretarias.setLayout(new javax.swing.BoxLayout(panelSecretarias, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(panelSecretarias);

        llenarTabla();
        llenarListas();
        jLabel6.setText("Nuevo");
    }

    public void llenarTabla() {
        String[] columnas = {"C\u00f3digo", "Nombre", "Doctores", "Secretarias"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Consultorio c : Proyecto2026.consultorios) {
            StringBuilder docs = new StringBuilder();
            for (int i = 0; i < c.doctores.size(); i++) {
                if (i > 0) docs.append(", ");
                docs.append(c.doctores.get(i).nombre);
            }

            StringBuilder secs = new StringBuilder();
            for (int i = 0; i < c.secretarias.size(); i++) {
                if (i > 0) secs.append(", ");
                secs.append(c.secretarias.get(i).nombre);
            }

            Object[] fila = {String.format("%03d", c.codigo), c.nombre, docs.toString(), secs.toString()};
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    public void llenarListas() {
        doctoresDisponibles = new ArrayList<>();
        checksDoctores = new ArrayList<>();
        panelDoctores.removeAll();

        for (Usuario u : Proyecto2026.usuarios) {
            if ("Doctor".equals(u.rol)) {
                doctoresDisponibles.add(u);
                JCheckBox cb = new JCheckBox(u.nombre);
                checksDoctores.add(cb);
                panelDoctores.add(cb);
            }
        }
        panelDoctores.revalidate();
        panelDoctores.repaint();

        secretariasDisponibles = new ArrayList<>();
        checksSecretarias = new ArrayList<>();
        panelSecretarias.removeAll();

        for (Usuario u : Proyecto2026.usuarios) {
            if ("Secretaria".equals(u.rol)) {
                secretariasDisponibles.add(u);
                JCheckBox cb = new JCheckBox(u.nombre);
                checksSecretarias.add(cb);
                panelSecretarias.add(cb);
            }
        }
        panelSecretarias.revalidate();
        panelSecretarias.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Consulta Consultorios:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("C\u00f3digo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Doctores:");

        jLabel5.setText("Secretarias:");

        jLabel6.setText("");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();

        if (i >= 0) {
            Proyecto2026.consultorios.remove(i);
            JOptionPane.showMessageDialog(this, "Consultorio eliminado.");
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = jTable1.getSelectedRow();

        if (i >= 0) {
            modificarConsultorio = Proyecto2026.consultorios.get(i);

            jLabel6.setText(String.format("%03d", modificarConsultorio.codigo));
            jTextField1.setText(modificarConsultorio.nombre);

            llenarListas();

            for (int d = 0; d < doctoresDisponibles.size(); d++) {
                for (Usuario doc : modificarConsultorio.doctores) {
                    if (doctoresDisponibles.get(d) == doc) {
                        checksDoctores.get(d).setSelected(true);
                        break;
                    }
                }
            }

            for (int s = 0; s < secretariasDisponibles.size(); s++) {
                for (Usuario sec : modificarConsultorio.secretarias) {
                    if (secretariasDisponibles.get(s) == sec) {
                        checksSecretarias.get(s).setSelected(true);
                        break;
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = jTextField1.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el consultorio.");
            return;
        }

        ArrayList<Usuario> doctoresSeleccionados = new ArrayList<>();
        for (int i = 0; i < checksDoctores.size(); i++) {
            if (checksDoctores.get(i).isSelected()) {
                doctoresSeleccionados.add(doctoresDisponibles.get(i));
            }
        }

        ArrayList<Usuario> secretariasSeleccionadas = new ArrayList<>();
        for (int i = 0; i < checksSecretarias.size(); i++) {
            if (checksSecretarias.get(i).isSelected()) {
                secretariasSeleccionadas.add(secretariasDisponibles.get(i));
            }
        }

        if (modificarConsultorio != null) {
            modificarConsultorio.nombre = nombre;
            modificarConsultorio.doctores = doctoresSeleccionados;
            modificarConsultorio.secretarias = secretariasSeleccionadas;
            JOptionPane.showMessageDialog(this, "Consultorio modificado.");
            llenarTabla();
            modificarConsultorio = null;
            jTextField1.setText("");
            jLabel6.setText("Nuevo");
            for (JCheckBox cb : checksDoctores) cb.setSelected(false);
            for (JCheckBox cb : checksSecretarias) cb.setSelected(false);
        } else {
            Consultorio nuevo = new Consultorio();
            nuevo.codigo = Proyecto2026.contadorConsultorios++;
            nuevo.nombre = nombre;
            nuevo.doctores = doctoresSeleccionados;
            nuevo.secretarias = secretariasSeleccionadas;
            Proyecto2026.consultorios.add(nuevo);
            JOptionPane.showMessageDialog(this, "Consultorio creado.");
            llenarTabla();
            jTextField1.setText("");
            jLabel6.setText("Nuevo");
            for (JCheckBox cb : checksDoctores) cb.setSelected(false);
            for (JCheckBox cb : checksSecretarias) cb.setSelected(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
