/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2026;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author rodri
 */
public class ConsultaCitas extends javax.swing.JFrame {

    private static final SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    /**
     * Creates new form ConsultaCitas
     */
    public ConsultaCitas() {
        initComponents();
        llenarTabla();

        // Cargar JSON visible solo para Secretaria.
        if (!"Secretaria".equals(Proyecto2026.usuarioLogin.rol)) {
            jButton4.setVisible(false);
        }
    }

    public void llenarTabla() {
        String[] columnas = {"Código", "Paciente", "Doctor", "Consultorio", "Fecha y hora", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Cita c : Proyecto2026.citas) {
            Object[] fila = {
                String.format("%03d", c.codigo),
                c.paciente.nombre,
                c.doctor.nombre,
                c.consultorio.nombre,
                SDF.format(c.fechaHora),
                c.estado
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Consulta Citas:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Marcar atendida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Exportar JSON");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exportar XML");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("Cargar JSON");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Receta médica");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita.");
            return;
        }
        Proyecto2026.citas.get(i).estado = "Atendida";
        JOptionPane.showMessageDialog(this, "Cita marcada como atendida.");
        llenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita.");
            return;
        }
        Proyecto2026.citas.remove(i);
        JOptionPane.showMessageDialog(this, "Cita eliminada.");
        llenarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita.");
            return;
        }
        Cita cita = Proyecto2026.citas.get(i);
        RecetaCita r = new RecetaCita(cita);
        r.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (Proyecto2026.citas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay citas para exportar.");
            return;
        }
        File downloads = obtenerCarpetaDownloads();
        File archivo = new File(downloads, "citas.json");
        try (FileWriter fw = new FileWriter(archivo)) {
            fw.write(construirJson());
            JOptionPane.showMessageDialog(this, "Citas exportadas a:\n" + archivo.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar JSON: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (Proyecto2026.citas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay citas para exportar.");
            return;
        }
        File downloads = obtenerCarpetaDownloads();
        File archivo = new File(downloads, "citas.xml");
        try {
            escribirXml(archivo);
            JOptionPane.showMessageDialog(this, "Citas exportadas a:\n" + archivo.getAbsolutePath());
        } catch (ParserConfigurationException | TransformerException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar XML: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private File obtenerCarpetaDownloads() {
        File downloads = new File(System.getProperty("user.home"), "Downloads");
        if (!downloads.exists()) downloads.mkdirs();
        return downloads;
    }

    private String construirJson() {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"citas\": [\n");
        for (int i = 0; i < Proyecto2026.citas.size(); i++) {
            Cita c = Proyecto2026.citas.get(i);
            sb.append("    {\n");
            sb.append("      \"codigo\": ").append(c.codigo).append(",\n");
            sb.append("      \"paciente\": \"").append(escaparJson(c.paciente.nombre)).append("\",\n");
            sb.append("      \"doctor\": \"").append(escaparJson(c.doctor.nombre)).append("\",\n");
            sb.append("      \"consultorio\": \"").append(escaparJson(c.consultorio.nombre)).append("\",\n");
            sb.append("      \"fechaHora\": \"").append(SDF.format(c.fechaHora)).append("\",\n");
            sb.append("      \"motivo\": \"").append(escaparJson(c.motivo)).append("\",\n");
            sb.append("      \"estado\": \"").append(escaparJson(c.estado)).append("\"\n");
            sb.append("    }");
            if (i < Proyecto2026.citas.size() - 1) sb.append(",");
            sb.append("\n");
        }
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }

    private String escaparJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }

    private void escribirXml(File archivo) throws ParserConfigurationException, TransformerException {
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        DocumentBuilder db = dbf.newDocumentBuilder();
        Document doc = db.newDocument();

        Element raiz = doc.createElement("citas");
        doc.appendChild(raiz);

        for (Cita c : Proyecto2026.citas) {
            Element ce = doc.createElement("cita");
            ce.appendChild(crearElemento(doc, "codigo", String.valueOf(c.codigo)));
            ce.appendChild(crearElemento(doc, "paciente", c.paciente.nombre));
            ce.appendChild(crearElemento(doc, "doctor", c.doctor.nombre));
            ce.appendChild(crearElemento(doc, "consultorio", c.consultorio.nombre));
            ce.appendChild(crearElemento(doc, "fechaHora", SDF.format(c.fechaHora)));
            ce.appendChild(crearElemento(doc, "motivo", c.motivo));
            ce.appendChild(crearElemento(doc, "estado", c.estado));
            raiz.appendChild(ce);
        }

        TransformerFactory tf = TransformerFactory.newInstance();
        Transformer t = tf.newTransformer();
        t.setOutputProperty(OutputKeys.INDENT, "yes");
        t.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
        t.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
        t.transform(new DOMSource(doc), new StreamResult(archivo));
    }

    private Element crearElemento(Document doc, String nombre, String valor) {
        Element e = doc.createElement(nombre);
        e.setTextContent(valor == null ? "" : valor);
        return e;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione el archivo JSON de citas");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos JSON (*.json)", "json"));
        File defaultFile = new File(System.getProperty("user.home"), "Documents/citas.json");
        if (defaultFile.exists()) {
            chooser.setSelectedFile(defaultFile);
        } else {
            chooser.setCurrentDirectory(new File(System.getProperty("user.home"), "Documents"));
        }
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File archivo = chooser.getSelectedFile();
        String contenido;
        try {
            contenido = new String(Files.readAllBytes(archivo.toPath()), StandardCharsets.UTF_8);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo JSON: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<String> objetos = extraerObjetos(contenido);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        sdf.setLenient(false);
        int importados = 0;
        int omitidos = 0;
        StringBuilder errores = new StringBuilder();

        for (int i = 0; i < objetos.size(); i++) {
            String obj = objetos.get(i);
            int num = i + 1;

            String nombrePaciente = extraerValor(obj, "paciente");
            String nombreDoctor = extraerValor(obj, "doctor");
            String nombreConsultorio = extraerValor(obj, "consultorio");
            String fechaTxt = extraerValor(obj, "fechaHora");
            String motivo = extraerValor(obj, "motivo");
            String estado = extraerValor(obj, "estado");

            Paciente p = buscarPaciente(nombrePaciente);
            if (p == null) {
                omitidos++;
                errores.append("Cita ").append(num).append(": paciente '").append(nombrePaciente).append("' no existe\n");
                continue;
            }
            Usuario d = buscarDoctor(nombreDoctor);
            if (d == null) {
                omitidos++;
                errores.append("Cita ").append(num).append(": doctor '").append(nombreDoctor).append("' no existe\n");
                continue;
            }
            Consultorio co = buscarConsultorio(nombreConsultorio);
            if (co == null) {
                omitidos++;
                errores.append("Cita ").append(num).append(": consultorio '").append(nombreConsultorio).append("' no existe\n");
                continue;
            }
            Date fh;
            try {
                fh = sdf.parse(fechaTxt);
            } catch (ParseException ex) {
                omitidos++;
                errores.append("Cita ").append(num).append(": fecha inválida '").append(fechaTxt).append("'\n");
                continue;
            }
            if (motivo.isEmpty()) {
                omitidos++;
                errores.append("Cita ").append(num).append(": motivo vacío\n");
                continue;
            }

            Cita nueva = new Cita();
            nueva.codigo = Proyecto2026.contadorCitas++;
            nueva.paciente = p;
            nueva.doctor = d;
            nueva.consultorio = co;
            nueva.fechaHora = fh;
            nueva.motivo = motivo;
            nueva.estado = (estado.equals("Atendida") || estado.equals("Pendiente")) ? estado : "Pendiente";
            Proyecto2026.citas.add(nueva);
            importados++;
        }

        llenarTabla();
        String resumen = "Citas importadas: " + importados + "\nOmitidas: " + omitidos;
        if (omitidos > 0) {
            resumen += "\n\nDetalle:\n" + errores.toString();
        }
        JOptionPane.showMessageDialog(this, resumen, "Carga JSON", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Extrae cada objeto {...} interno (sin llaves anidadas) del JSON.
    private List<String> extraerObjetos(String json) {
        List<String> objetos = new ArrayList<>();
        java.util.Deque<Integer> pila = new java.util.ArrayDeque<>();
        for (int i = 0; i < json.length(); i++) {
            char ch = json.charAt(i);
            if (ch == '{') {
                pila.push(i);
            } else if (ch == '}') {
                if (!pila.isEmpty()) {
                    int start = pila.pop();
                    String bloque = json.substring(start, i + 1);
                    if (bloque.indexOf('{', 1) == -1) {
                        objetos.add(bloque);
                    }
                }
            }
        }
        return objetos;
    }

    // Extrae el valor (texto o número) asociado a "clave" dentro de un objeto JSON.
    private String extraerValor(String objeto, String clave) {
        String patron = "\"" + clave + "\"";
        int idx = objeto.indexOf(patron);
        if (idx == -1) {
            return "";
        }
        int colon = objeto.indexOf(':', idx + patron.length());
        if (colon == -1) {
            return "";
        }
        int p = colon + 1;
        while (p < objeto.length() && Character.isWhitespace(objeto.charAt(p))) {
            p++;
        }
        if (p >= objeto.length()) {
            return "";
        }
        if (objeto.charAt(p) == '"') {
            int end = objeto.indexOf('"', p + 1);
            if (end == -1) {
                return "";
            }
            return objeto.substring(p + 1, end);
        }
        int end = p;
        while (end < objeto.length()
                && objeto.charAt(end) != ','
                && objeto.charAt(end) != '}'
                && !Character.isWhitespace(objeto.charAt(end))) {
            end++;
        }
        return objeto.substring(p, end).trim();
    }

    private Paciente buscarPaciente(String nombre) {
        for (Paciente p : Proyecto2026.pacientes) {
            if (p.nombre.equalsIgnoreCase(nombre)) {
                return p;
            }
        }
        return null;
    }

    private Usuario buscarDoctor(String nombre) {
        for (Usuario u : Proyecto2026.usuarios) {
            if ("Doctor".equals(u.rol) && u.nombre.equalsIgnoreCase(nombre)) {
                return u;
            }
        }
        return null;
    }

    private Consultorio buscarConsultorio(String nombre) {
        for (Consultorio c : Proyecto2026.consultorios) {
            if (c.nombre.equalsIgnoreCase(nombre)) {
                return c;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
