/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2026;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author carlos
 */
public class ConsultaPacientes extends javax.swing.JFrame {

    public Paciente modificarPaciente;

    /**
     * Creates new form ConsultaPacientes
     */
    public ConsultaPacientes() {
        initComponents();
        llenarTabla();
        jLabel6.setText("Nuevo");

        // Cargar XML visible para Doctor y Secretaria.
        String rol = Proyecto2026.usuarioLogin.rol;
        if (!"Doctor".equals(rol) && !"Secretaria".equals(rol)) {
            jButton7.setVisible(false);
        }
    }

    public void llenarTabla() {
        String[] columnas = {"Código", "Nombre", "Edad", "Peso", "Estatura", "Teléfonos"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Paciente p : Proyecto2026.pacientes) {
            Object[] fila = {
                String.format("%03d", p.codigo),
                p.nombre,
                p.edad,
                p.peso,
                p.estatura,
                p.telefonos
            };
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    private void limpiarCampos() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jLabel6.setText("Nuevo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Consulta Pacientes:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Exportar JSON");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exportar XML");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cargar XML");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Peso (kg):");

        jLabel6.setText("");

        jLabel7.setText("Estatura (m):");

        jLabel8.setText("Teléfonos:");

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();

        if (i >= 0) {
            Proyecto2026.pacientes.remove(i);
            JOptionPane.showMessageDialog(this, "Paciente eliminado.");
            llenarTabla();
            if (modificarPaciente != null) {
                modificarPaciente = null;
                limpiarCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = jTable1.getSelectedRow();

        if (i >= 0) {
            modificarPaciente = Proyecto2026.pacientes.get(i);
            jLabel6.setText(String.format("%03d", modificarPaciente.codigo));
            jTextField1.setText(modificarPaciente.nombre);
            jTextField2.setText(String.valueOf(modificarPaciente.edad));
            jTextField3.setText(String.valueOf(modificarPaciente.peso));
            jTextField4.setText(String.valueOf(modificarPaciente.estatura));
            jTextField5.setText(modificarPaciente.telefonos);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = jTextField1.getText().trim();
        String edadTxt = jTextField2.getText().trim();
        String pesoTxt = jTextField3.getText().trim();
        String estaturaTxt = jTextField4.getText().trim();
        String telefonos = jTextField5.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del paciente.");
            return;
        }

        int edad;
        double peso;
        double estatura;
        try {
            edad = Integer.parseInt(edadTxt);
            if (edad < 0) {
                JOptionPane.showMessageDialog(this, "La edad no puede ser negativa.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Edad inválida.");
            return;
        }
        try {
            peso = Double.parseDouble(pesoTxt);
            if (peso <= 0) {
                JOptionPane.showMessageDialog(this, "El peso debe ser mayor a 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Peso inválido.");
            return;
        }
        try {
            estatura = Double.parseDouble(estaturaTxt);
            if (estatura <= 0) {
                JOptionPane.showMessageDialog(this, "La estatura debe ser mayor a 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Estatura inválida.");
            return;
        }

        if (telefonos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese al menos un teléfono.");
            return;
        }

        if (modificarPaciente != null) {
            modificarPaciente.nombre = nombre;
            modificarPaciente.edad = edad;
            modificarPaciente.peso = peso;
            modificarPaciente.estatura = estatura;
            modificarPaciente.telefonos = telefonos;
            JOptionPane.showMessageDialog(this, "Paciente modificado.");
            llenarTabla();
            modificarPaciente = null;
        } else {
            Paciente nuevo = new Paciente();
            nuevo.codigo = Proyecto2026.contadorPacientes++;
            nuevo.nombre = nombre;
            nuevo.edad = edad;
            nuevo.peso = peso;
            nuevo.estatura = estatura;
            nuevo.telefonos = telefonos;
            Proyecto2026.pacientes.add(nuevo);
            JOptionPane.showMessageDialog(this, "Paciente creado.");
            llenarTabla();
        }
        limpiarCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (Proyecto2026.pacientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay pacientes para exportar.");
            return;
        }
        File downloads = obtenerCarpetaDownloads();
        File archivo = new File(downloads, "pacientes.json");
        try (FileWriter fw = new FileWriter(archivo)) {
            fw.write(construirJson());
            JOptionPane.showMessageDialog(this, "Pacientes exportados a:\n" + archivo.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar JSON: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (Proyecto2026.pacientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay pacientes para exportar.");
            return;
        }
        File downloads = obtenerCarpetaDownloads();
        File archivo = new File(downloads, "pacientes.xml");
        try {
            escribirXml(archivo);
            JOptionPane.showMessageDialog(this, "Pacientes exportados a:\n" + archivo.getAbsolutePath());
        } catch (ParserConfigurationException | TransformerException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar XML: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private File obtenerCarpetaDownloads() {
        File downloads = new File(System.getProperty("user.home"), "Downloads");
        if (!downloads.exists()) {
            downloads.mkdirs();
        }
        return downloads;
    }

    private String construirJson() {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"pacientes\": [\n");
        for (int i = 0; i < Proyecto2026.pacientes.size(); i++) {
            Paciente p = Proyecto2026.pacientes.get(i);
            sb.append("    {\n");
            sb.append("      \"codigo\": ").append(p.codigo).append(",\n");
            sb.append("      \"nombre\": \"").append(escaparJson(p.nombre)).append("\",\n");
            sb.append("      \"edad\": ").append(p.edad).append(",\n");
            sb.append("      \"peso\": ").append(p.peso).append(",\n");
            sb.append("      \"estatura\": ").append(p.estatura).append(",\n");
            sb.append("      \"telefonos\": \"").append(escaparJson(p.telefonos)).append("\"\n");
            sb.append("    }");
            if (i < Proyecto2026.pacientes.size() - 1) sb.append(",");
            sb.append("\n");
        }
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }

    private String escaparJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }

    private void escribirXml(File archivo) throws ParserConfigurationException, TransformerException {
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        DocumentBuilder db = dbf.newDocumentBuilder();
        Document doc = db.newDocument();

        Element raiz = doc.createElement("pacientes");
        doc.appendChild(raiz);

        for (Paciente p : Proyecto2026.pacientes) {
            Element pe = doc.createElement("paciente");
            pe.appendChild(crearElemento(doc, "codigo", String.valueOf(p.codigo)));
            pe.appendChild(crearElemento(doc, "nombre", p.nombre));
            pe.appendChild(crearElemento(doc, "edad", String.valueOf(p.edad)));
            pe.appendChild(crearElemento(doc, "peso", String.valueOf(p.peso)));
            pe.appendChild(crearElemento(doc, "estatura", String.valueOf(p.estatura)));
            pe.appendChild(crearElemento(doc, "telefonos", p.telefonos));
            raiz.appendChild(pe);
        }

        TransformerFactory tf = TransformerFactory.newInstance();
        Transformer t = tf.newTransformer();
        t.setOutputProperty(OutputKeys.INDENT, "yes");
        t.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
        t.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
        t.transform(new DOMSource(doc), new StreamResult(archivo));
    }

    private Element crearElemento(Document doc, String nombre, String valor) {
        Element e = doc.createElement(nombre);
        e.setTextContent(valor == null ? "" : valor);
        return e;
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione el archivo XML de pacientes");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos XML (*.xml)", "xml"));
        File defaultFile = new File(System.getProperty("user.home"), "Documents/pacientes.xml");
        if (defaultFile.exists()) {
            chooser.setSelectedFile(defaultFile);
        } else {
            chooser.setCurrentDirectory(new File(System.getProperty("user.home"), "Documents"));
        }
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File archivo = chooser.getSelectedFile();
        int importados = 0;
        int omitidos = 0;
        StringBuilder errores = new StringBuilder();

        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            Document doc = db.parse(archivo);
            doc.getDocumentElement().normalize();

            NodeList nodos = doc.getElementsByTagName("paciente");
            for (int i = 0; i < nodos.getLength(); i++) {
                Element el = (Element) nodos.item(i);
                int numPaciente = i + 1;

                String nombre = obtenerTexto(el, "nombre");
                String edadTxt = obtenerTexto(el, "edad");
                String pesoTxt = obtenerTexto(el, "peso");
                String estaturaTxt = obtenerTexto(el, "estatura");
                String telefonos = obtenerTexto(el, "telefonos");

                if (nombre.isEmpty()) {
                    omitidos++;
                    errores.append("Paciente ").append(numPaciente).append(": nombre vacío\n");
                    continue;
                }
                int edad;
                double peso, estatura;
                try {
                    edad = Integer.parseInt(edadTxt);
                    peso = Double.parseDouble(pesoTxt);
                    estatura = Double.parseDouble(estaturaTxt);
                } catch (NumberFormatException e) {
                    omitidos++;
                    errores.append("Paciente ").append(numPaciente).append(": valores numéricos inválidos\n");
                    continue;
                }
                if (edad < 0 || peso <= 0 || estatura <= 0) {
                    omitidos++;
                    errores.append("Paciente ").append(numPaciente).append(": valores fuera de rango\n");
                    continue;
                }

                Paciente nuevo = new Paciente();
                nuevo.codigo = Proyecto2026.contadorPacientes++;
                nuevo.nombre = nombre;
                nuevo.edad = edad;
                nuevo.peso = peso;
                nuevo.estatura = estatura;
                nuevo.telefonos = telefonos;
                Proyecto2026.pacientes.add(nuevo);
                importados++;
            }
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo XML: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        llenarTabla();
        String resumen = "Pacientes importados: " + importados + "\nOmitidos: " + omitidos;
        if (omitidos > 0) {
            resumen += "\n\nDetalle:\n" + errores.toString();
        }
        JOptionPane.showMessageDialog(this, resumen, "Carga XML", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    private String obtenerTexto(Element padre, String etiqueta) {
        NodeList lista = padre.getElementsByTagName(etiqueta);
        if (lista.getLength() == 0 || lista.item(0).getTextContent() == null) {
            return "";
        }
        return lista.item(0).getTextContent().trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
