/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2026;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class ConsultaUsuarios extends javax.swing.JFrame {

    public Usuario modificarUsuario;
    /**
     * Creates new form ConsultaUsuarios
     */
    public ConsultaUsuarios() {
        initComponents();
        
        llenarTabla();
        
        jLabel5.setText("");
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11));
        jLabel5.setVisible(false);
    }
    
    public void llenarTabla(){
        String[] columnas = {"Usuario", "Password", "Rol"};
        DefaultTableModel modelo = new DefaultTableModel(columnas,0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for(Usuario u: Proyecto2026.usuarios){
            Object[] fila = {u.nombre,u.password,u.rol};
            modelo.addRow(fila);
        }
        
        jTable1.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Consulta Usuarios:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        jLabel3.setText("Password:");

        jLabel4.setText("Rol:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar CSV");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Doctor", "Secretaria" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int i = jTable1.getSelectedRow();
        
        if(i>0){
            Proyecto2026.usuarios.remove(i);
            JOptionPane.showMessageDialog(this, "Usuario eliminado.");
            llenarTabla();
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int i = jTable1.getSelectedRow();
        
        if(i>=0){
            modificarUsuario = Proyecto2026.usuarios.get(i);
            jTextField1.setText(modificarUsuario.nombre);
            jTextField2.setText(modificarUsuario.password);
           
            switch(modificarUsuario.rol){
                case "Administrador"->{
                    jComboBox1.setSelectedIndex(0);
                }
                case "Doctor"->{
                    jComboBox1.setSelectedIndex(1);
                }
                case "Secretaria"->{
                    jComboBox1.setSelectedIndex(2);
                }
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String password = jTextField2.getText();
        String errorPassword = validarPassword(password);
        if(errorPassword != null){
            jLabel5.setText("<html>" + errorPassword + "</html>");
            jLabel5.setVisible(true);
            return;
        }
        jLabel5.setVisible(false);
        
        if(modificarUsuario!=null){
            modificarUsuario.nombre = jTextField1.getText();
            modificarUsuario.password = password;
            modificarUsuario.rol = jComboBox1.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, "Usuario modificado.");
            llenarTabla();
            modificarUsuario = null;
            jTextField1.setText("");
            jTextField2.setText("");
            jLabel5.setVisible(false);
        }else{
            Usuario nuevo = new Usuario();
            nuevo.nombre = jTextField1.getText();
            nuevo.password = password;
            nuevo.rol = jComboBox1.getSelectedItem().toString();
            Proyecto2026.usuarios.add(nuevo);
            JOptionPane.showMessageDialog(this, "Usuario Creado.");
            llenarTabla();
            jTextField1.setText("");
            jTextField2.setText("");
            jLabel5.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione el archivo CSV de usuarios");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos CSV (*.csv)", "csv"));
        File defaultFile = new File(System.getProperty("user.home"), "Documents/usuarios.csv");
        if (defaultFile.exists()) {
            chooser.setSelectedFile(defaultFile);
        } else {
            chooser.setCurrentDirectory(new File(System.getProperty("user.home"), "Documents"));
        }

        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File archivo = chooser.getSelectedFile();
        int importados = 0;
        int omitidos = 0;
        StringBuilder errores = new StringBuilder();

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            int numLinea = 0;
            while ((linea = br.readLine()) != null) {
                numLinea++;
                if (linea.trim().isEmpty()) continue;
                if (numLinea == 1 && linea.toLowerCase().startsWith("nombre")) continue;

                String[] campos = linea.split(",", -1);
                if (campos.length < 3) {
                    omitidos++;
                    errores.append("Línea ").append(numLinea).append(": columnas insuficientes\n");
                    continue;
                }

                String nombre = campos[0].trim();
                String password = campos[1].trim();
                String rol = campos[2].trim();
                String nombreConsultorio = campos.length >= 4 ? campos[3].trim() : "";

                if (nombre.isEmpty() || password.isEmpty()) {
                    omitidos++;
                    errores.append("Línea ").append(numLinea).append(": nombre o password vacío\n");
                    continue;
                }
                if (!"Administrador".equals(rol) && !"Doctor".equals(rol) && !"Secretaria".equals(rol)) {
                    omitidos++;
                    errores.append("Línea ").append(numLinea).append(": rol inválido '").append(rol).append("'\n");
                    continue;
                }
                if (validarPassword(password) != null) {
                    omitidos++;
                    errores.append("Línea ").append(numLinea).append(": password no cumple requisitos\n");
                    continue;
                }
                if (existeUsuario(nombre)) {
                    omitidos++;
                    errores.append("Línea ").append(numLinea).append(": usuario '").append(nombre).append("' ya existe\n");
                    continue;
                }

                Consultorio consultorio = null;
                if (!nombreConsultorio.isEmpty()) {
                    consultorio = buscarConsultorio(nombreConsultorio);
                    if (consultorio == null) {
                        omitidos++;
                        errores.append("Línea ").append(numLinea).append(": consultorio '").append(nombreConsultorio).append("' no encontrado\n");
                        continue;
                    }
                }

                Usuario nuevo = new Usuario();
                nuevo.nombre = nombre;
                nuevo.password = password;
                nuevo.rol = rol;
                nuevo.consultorio = consultorio;
                Proyecto2026.usuarios.add(nuevo);
                importados++;
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        llenarTabla();
        String resumen = "Usuarios importados: " + importados + "\nOmitidos: " + omitidos;
        if (omitidos > 0) {
            resumen += "\n\nDetalle:\n" + errores.toString();
        }
        JOptionPane.showMessageDialog(this, resumen, "Carga CSV", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private boolean existeUsuario(String nombre) {
        for (Usuario u : Proyecto2026.usuarios) {
            if (u.nombre.equalsIgnoreCase(nombre)) return true;
        }
        return false;
    }

    private Consultorio buscarConsultorio(String nombre) {
        for (Consultorio c : Proyecto2026.consultorios) {
            if (c.nombre.equalsIgnoreCase(nombre)) return c;
        }
        return null;
    }

    private String validarPassword(String password) {
        if (password.length() < 6) {
            return "La contraseña debe tener al menos 6 caracteres.";
        }
        if (!password.matches(".*[0-9].*")) {
            return "La contraseña debe contener al menos un número.";
        }
        if (!password.matches(".*[A-Z].*")) {
            return "La contraseña debe contener al menos una letra mayúscula.";
        }
        if (!password.matches(".*[a-z].*")) {
            return "La contraseña debe contener al menos una letra minúscula.";
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
